# Figuren fuer TOPPLER (eigene Entwuerfe), 16x16, '.' = durchsichtig
# K schwarz B blau G gruen C cyan R rot M magenta Y gelb W weiss
LIB_F = [
"...KK......KK...",
"....KKKKKKKK....",
"....KggggggK....",
"...KWWWGGWWWK...",
"..BKWBWGGWBWKB..",
"BBBKWWWGGWWWKBBB",
"BCCKGGGGGGGGKCCB",
".BCKGKGGGGKGKCB.",
".BCKGGKKKKGGKCB.",
"..BKGGGGGGGGKB..",
"...BKGggggGKB...",
"....KGGGGGGK....",
".....KggggK.....",
"....K.KKKK.K....",
"...K..K..K..K...",
"..KK.KK..KK.KK..",
]
LIB_B = [
"...KK......KK...",
"....KKKKKKKK....",
"....KWWGGWWK....",
"...KWWWGGWWWK...",
"..BBBBGGGGBBBB..",
"BBBCCCBGGBCCCBBB",
"BCCCCCBGGBCCCCCB",
".BCCCCBGGBCCCCB.",
".BCCCBKGGKBCCCB.",
"..BBBKGGGGKBBB..",
"...BKGGBBGGKB...",
"....KGGBBGGK....",
".....KGBBGK.....",
"....K.KBBK.K....",
"...K..KBBK..K...",
"..KK.KK..KK.KK..",
]
LIB_R = [
"............KK..",
"........KKKKKK..",
".......KGGGGK...",
"...BB..KGWWWK...",
"..BCCBKGGWWBK...",
".BCCCKGGGWWBGK..",
"BCCCKGGGGGGGGK..",
".BBCKGGGGGGKKK..",
"..BBKGGGGGGGGK..",
"KKKKKGGGGGGGK...",
"BGGGGGGGGGGK....",
"KKKKKKggggK.....",
"......KKKKK.....",
"......K...K.....",
".....KK..KK.....",
"................",
]
DUMMVOGEL = [        # von vorn
"......M..M......",
"....M.MMMM.M....",
"...KKKKMMKKKK...",
"..KWWWWKKWWWWK..",
"..KWWKWKKWKWWK..",
"..KWWKWKKWKWWK..",
"..KWWWWKKWWWWK..",
"...KKKKRRKKKK...",
"..KRRRYYYYRRRK..",
".KrrRRKYYKRRrrK.",
".KrrRRRKKRRRrrK.",
".KrrRRRRRRRRrrK.",
"..KrRRRRRRRRrK..",
"...KKKKKKKKKK...",
".....K....K.....",
"....KK....KK....",
]
VOGEL_GEB = [        # gebueckt
"................",
"................",
"................",
"......M..M......",
"....M.MMMM.M....",
"...KKKKMMKKKK...",
"..KWWWWKKWWWWK..",
"..KWWKWKKWKWWK..",
"..KWWWWKKWWWWK..",
"..KKKKKRRKKKKK..",
".KRRRRYYYYRRRRK.",
"KrrRRRKYYKRRRrrK",
"KrrRRRRKKRRRRrrK",
".KrrRRRRRRRRrrK.",
"..KKKKKKKKKKKK..",
"..KK........KK..",
]
VOGEL_R = [          # nach rechts
"......M.........",
"....MMMM........",
".....KKKKKK.....",
"....KWWWWWWK....",
"....KWWWWKWK....",
"....KWWWWKWKYY..",
"....KWWWWWWKYYY.",
"...KKKKKKKKYYY..",
"..KRRRRRRRRKY...",
".KRRRRRRRRRRK...",
"KRRrrrrrRRRRK...",
"KRRRrrrrRRRRK...",
".KRRRRRRRRRK....",
"..KKKKKKKKK.....",
".....K..K.......",
"....KK.KK.......",
]
KAEFER = [
"................",
"...WW......WW...",
"....WW....WW....",
"......KKKK......",
".....KWKKWK.....",
".....KKKKKK.....",
"...KKBBKKBBKK...",
"WWWKBBBKKBBBKWWW",
"...KBWBKKBWBK...",
"...KBBBKKBBBK...",
"WWWKBBBKKBBBKWWW",
"...KBBBKKBBBK...",
"...KBBBKKBBBK...",
"WWWKBBBKKBBBKWWW",
"....KBBKKBBK....",
".....KKKKKK.....",
]
KROETE = [            # Kroete, gelb
"................",
"................",
"...KKK....KKK...",
"..KWKWK..KWKWK..",
"..KWWWKKKKWWWK..",
"..KYYYYYYYYYYK..",
".KYYYYYYYYYYYYK.",
".KYYKKKKKKKKYYK.",
".KYYYYYYYYYYYYK.",
"KYYGYYYYYYYYGYYK",
"KYYYYYGYYYYYYYYK",
".KYYYYYYYYGYYYK.",
"KKYYKKKKKKKKYYKK",
"KYYK........KYYK",
".KK..........KK.",
"................",
]
BIENE = [            # Biene, rot, von der Seite
"................",
"...WWW..........",
"..WCCCW.WWW.....",
"..WCCCCWCCCW..W.",
"...WCCCWCCW..W..",
"....WWKWWW..W...",
"...KKRRKRRKKKK..",
"..KRRKRRKRRKKKKK",
".KRRRKRRKRRKKWKK",
"KKRRRKRRKRRKKKKK",
".KRRRKRRKRRKKKK.",
"..KRRKRRKRRKK...",
"...KKKKKKKKK....",
"....W.W.W.W.....",
"...W.W.W.W......",
"................",
]
BLUETE = [            # Seerosenbluete, pink
"................",
".......MM.......",
"......MWWM......",
"..MM..MWMM..MM..",
"..MWMMMWMMMMWM..",
"...MWMMYYMMWM...",
"...MMMYYYYMMM...",
".MMMMYYYYYYMMMM.",
"MWWWMMYYYYMMWWWM",
".MMMMMMYYMMMMMM.",
"...MMWMMMMWMM...",
"..MWMMMWWMMMWM..",
"..MM..MWWM..MM..",
"......MMMM......",
"................",
"................",
]

def mirror(rows): return [r[::-1] for r in rows]
LIB_L = mirror(LIB_R)
VOGEL_L = mirror(VOGEL_R)

# ---- Titelbild-Animationen (ab V0.17) ----
LIB_FLY = [          # Libelle im Flug: Fluegel oben, Beine haengen
"BB.KK......KK.BB",
"BCB.KKKKKKKK.BCB",
"BCCBKggggggKBCCB",
".BCKWWWGGWWWKCB.",
"..BKWBWGGWBWKB..",
"...KWWWGGWWWK...",
"...KGGGGGGGGK...",
"...KGKGGGGKGK...",
"...KGGKKKKGGK...",
"...KGGGGGGGGK...",
"...BKGggggGKB...",
"....KGGGGGGK....",
".....KggggK.....",
".....K.KK.K.....",
".....K....K.....",
"....K......K....",
]
VOGEL_ZU = [         # Dummvogel blinzelt (Lider rot, Augen zu)
"......M..M......",
"....M.MMMM.M....",
"...KKKKMMKKKK...",
"..KRRRRKKRRRRK..",
"..KRRRRKKRRRRK..",
"..KKKKKKKKKKKK..",
"..KWWWWKKWWWWK..",
"...KKKKRRKKKK...",
"..KRRRYYYYRRRK..",
".KrrRRKYYKRRrrK.",
".KrrRRRKKRRRrrK.",
".KrrRRRRRRRRrrK.",
"..KrRRRRRRRRrK..",
"...KKKKKKKKKK...",
".....K....K.....",
"....KK....KK....",
]
COIN_N = [           # Muenze halb gedreht
"......KKKK......",
".....KYYYYK.....",
"....KYWYYYYK....",
"....KWYYYYYK....",
"....KWYYYYYK....",
"....KYYYYYYK....",
"....KYYYYYYK....",
"....KYYYYYYK....",
"....KYYYYYYK....",
"....KYYYYYYK....",
"....KYYYYYYK....",
"....KYYYYYYK....",
"....KYYYYYYK....",
".....KYYYYK.....",
".....KYYYYK.....",
"......KKKK......",
]
COIN_E = [           # Muenze von der Kante
".......KK.......",
"......KYYK......",
"......KWYK......",
"......KWYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
"......KYYK......",
".......KK.......",
]
KROETE_KOPF = [      # Kroetenkopf, schaut aus dem Wasser (wird von unten abgeschnitten)
"................",
"..KKKK....KKKK..",
".KWWWWK..KWWWWK.",
".KWWKWK..KWKWWK.",
".KWWKWKKKKWKWWK.",
".KYWWWYYYYWWWYK.",
"KYYYYYYYYYYYYYYK",
"KYYGYYYYYYYYGYYK",
"KYYYYYYYYYYYYYYK",
"KYKKKKKKKKKKKKYK",
"KYYKYYYYYYYYKYYK",
".KYYKKKKKKKKYYK.",
"..KYYYYYYYYYYK..",
"...KKKKKKKKKK...",
"................",
"................",
]
def emerge(rows, n):
    """nur die oberen n Zeilen, unten buendig"""
    return ['.' * 16] * (16 - n) + rows[:n]
KROETE_K1 = emerge(KROETE_KOPF, 6)
KROETE_K2 = emerge(KROETE_KOPF, 10)
KROETE_K3 = emerge(KROETE_KOPF, 14)
